name: wedlm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - blinker==1.9.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - einops==0.8.1
      - filelock==3.20.0
      - flash-attn==2.8.3
      - flask==3.1.2
      - fsspec==2025.12.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.6.1
      - ninja==1.13.0
      - numpy==2.4.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - psutil==7.2.1
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - sympy==1.13.1
      - tokenizers==0.22.1
      - torch==2.5.1+cu121
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.1.0
      - typing-extensions==4.15.0
      - urllib3==2.6.2
      - wedlm==0.1.0
      - werkzeug==3.1.4
      - xxhash==3.6.0
