name: bdiff
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - expat=2.7.3
  - faiss=1.9.0
  - faiss-cpu=1.9.0
  - filelock=3.20.0
  - gmp=6.3.0
  - gmpy2=2.2.2
  - icu=73.1
  - intel-openmp=2025.0.0
  - jinja2=3.1.6
  - ld_impl_linux-64=2.44
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libexpat=2.7.3
  - libfaiss=1.9.0
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - liblapack=3.9.0
  - libnpp=12.0.2.50
  - libnsl=2.0.0
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - markupsafe=3.0.2
  - mkl=2020.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.6.1
  - numpy=1.26.4
  - ocl-icd=2.3.3
  - opencl-headers=2025.07.22
  - openssl=3.6.0
  - packaging=25.0
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - readline=8.3
  - scipy=1.17.0
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - torchtriton=3.1.0
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - pip:
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.2.0
      - deepspeed==0.18.0
      - dill==0.4.0
      - dllm==0.1.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - h11==0.16.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - iniconfig==2.3.0
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.16
      - ninja==1.13.0
      - omegaconf==2.3.0
      - pandas==2.3.3
      - peft==0.17.1
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - sentence-transformers==5.2.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.49.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tokenizers==0.22.2
      - tqdm==4.67.1
      - transformers==4.57.0
      - typeguard==4.4.4
      - typing-inspection==0.4.2
      - tyro==1.0.4
      - tzdata==2025.3
      - urllib3==2.6.3
      - wandb==0.23.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /nfs/home/cbarbour/.conda/envs/bdiff
